language: ruby
rvm:
- 2.2.0
- 2.1.5
- 2.0.0
- 1.9.3
- jruby-1.7.9
- jruby-head
notifications:
  slack:
    secure: fXYggrDRoLB/4yvyW0kWwyrV5yWa/GC0btPyGu7Hx6ZOaXDC+ejiXSfx7nRyY+uZBs5UF12O4gkUXwBbnWDT5JtQRxzZd5s0cyeGQfAakALexI+FuR2jDcV1prCCaYI4IYoUt61MlfDmuCYVm8hGZ3qsgk/GPHHPnZ8a1FBd2ls=
matrix:
  allow_failures:
    - rvm: jruby-head